version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "5432:5432"
    environment:
      - MYSQL-USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=melp
  app:
    container_name: melp-crud
    image: melp-crud
    working_dir: /app
    build: 
      context: docker
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env.local
    command: >
      sh -c 'npm i 
      && rm -rf dist
      && npm run build
      && npm run start:dev'